### ISSUE TITLE
[P0] [BUG] Update the MEC-Accelerator ALERTS dashboard table with the REAL Camera name/IDs in the column

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#103]
At least as PO, initially, hide the column of "Camera name/ID" in the ALERTS dashboard.

Later as P1 or P2, let's add/propagate the real CAMERA NAME/ID we used when provisioning to the ALERTS dashboard.

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/bf640114-4b48-44fd-bf1e-f0a5aa366b53)

**Comment by CESARDELATORRE** [comment]
Moving to P0 since we need to have this issue solve by MWC, please, so we show the ream CAM name in the MEC-Accelerator.

**Comment by 3lcarry** [comment]
Ready to test

**Comment by CESARDELATORRE** [comment]
Closing it, fixed.
