### ISSUE TITLE
[P0] Easy UI changes but important changes in "Control Plane app" menus

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#107]
P0 son these changes are available for the DEMO VIDEO RECORDING we're doing.

Also, add the link to open the MEC-Accelerator in a different browser tab, as in the menus below:

<img width="807" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/62277d13-4d40-41aa-9ad1-c9c9a90c3998">

**Comment by 3lcarry** [comment]
I've pushed a new version of the control plane ui image. Btw the alerts ui url is fetch from the env variable NEXT_PUBLIC_ALERTS_UI_URI, I will update the k8s deployment to include this setting

**Comment by CESARDELATORRE** [comment]
This is done, but check this related minor bug, though:

https://github.com/Azure/mec-app-solution-accelerator/issues/117
