### ISSUE TITLE
[P1] Add additional columns to SIM list table

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#108]
Have the following fields/columns in the SIMs table, in the following order (Put exactly those names below):

**- SIM name (Put SIM name instead of just "Name" like we have now)
- IMSI
- IP
- SIM policy
- SIM group
- SIM state**

Basically, like Azure portal **highlighted in yellow below**, **plus the IP**:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/4e7a61be-8125-4ac4-b2fc-06e497845b83)

Currently we just have SIM name, IMSI and IP:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/dd3ec279-496b-46bd-b8ec-674cf7a47b65)

**Comment by 3lcarry** [comment]
Ready to test

**Comment by CESARDELATORRE** [comment]
Closing this issue, it's implemented and working. :)
