### ISSUE TITLE
[P0] [BUG] Cameras dashboard with provisioned cameras do not work in k3s in VM (125GB) in ASE BCN

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#120]
Three BUGS related:

- 1. RTSP container does not work in dashboard
- 2. XINGTERA 5G camera RTSP does not work in dashboard, neither. 
- 3. XINGTERA 5G camera HTTP .FLV Url does not work in dashboard, neither. 

REPRO:

ENVIRONMENT:

In **k3s**, with **VM IP** **172.30.1.76** (BCN environment)

**1.**

I created a camera simularion RTSP container in the cameras provisioning:

RTSP:  rtsp://172.30.1.76:8554/video

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/88c0ec68-5ce9-4ea3-afd6-ab0224c9d176)

But then it's not working in the CAMERA DASHBOARD:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/15efdf37-c3a5-45b4-b2c5-ee23666b0f38)

However, the RTSP is working in the MEC-Accelerator:

Also, it works properly in VLC PLAYER from the NUC:

<img width="645" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/086e89a8-eed2-42d0-914c-f6a73186ed87">

**2.**

I provisioned the XINGTERA 5G camera:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/91980b15-17e0-45bd-9599-ba180be55515)

But then it's not working in the CAMERA DASHBOARD:
![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/3249e400-87ae-435f-9281-0bff4ea83d48)

However, the XINGTERA 5G camera is working in the MEC-Accelerator:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/1bb1ce74-734a-4093-8c0c-7452fde8e98e)

Also, it works properly in VLC PLAYER from the NUC:

<img width="539" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/3368b073-fc70-4f23-bc7c-066021e35bac">

So, there's a BUG in the CAMERAS dashboard?

**Comment by CESARDELATORRE** [comment]
Related bug:
https://github.com/Azure/mec-app-solution-accelerator/issues/97

**Comment by CESARDELATORRE** [comment]
I have also tested this HTTP Url in the BCN-VM-k3s today, and it does not work, neither:

This URL works in VLC Player in BCN from the NUC:

http://admin:admin@192.0.2.130:80/live/main.flv

<img width="590" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/d461d292-7650-4817-904e-4c4817bfbb27">

I put the same HTTP URL in the camera:

<img width="614" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/b638e046-27f2-44c5-b455-a1c37ff2ba4a">

However, it doesn't work, neither, in the cameras dashboard:

<img width="800" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/df29d7cf-07ba-4ed7-97dc-ea5ba5f616d9">

**Comment by 3lcarry** [comment]
@CESARDELATORRE  Fix the issue with the RTSP converter when the camera id has a space. Now it should work, checking the flv player

**Comment by CESARDELATORRE** [comment]
Fixed, closing it.
