### ISSUE TITLE
[P1] Change from "HLS Uri" label to "Http Uri"?

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#128]
Since the Xingtera Http uri is not HLS...?

<img width="939" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/a858b466-6b8c-4542-9482-30431fb9f674">

**Comment by CESARDELATORRE** [comment]
I think this is fixed.. I must have a different version installed in the k3s?

How can we force the IMAGE upgrade in K8s?

In the NUC it's fixed:
https://github.com/Azure/mec-app-solution-accelerator/issues/129

**Comment by 3lcarry** [comment]
Updated

**Comment by CESARDELATORRE** [comment]
Hide the field HTTP since it's not fully supported.
