### ISSUE TITLE
[P0] In K8s-Docker-Desktop my laptop/Windows 11 --> SIMs Provisioning shows up empty

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#131]
In K8s-Docker-Desktop my laptop/Windows 11 --> SIMs Provisioning shows up empty

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/b24b1b38-254b-47cd-b17a-7d61ecae0f32)

I have configured the "13-control-plane-api-config-map.yaml" agains BCN environment in AP5GC cloud.
In fact, it's the same config I used for the k3s which is working... so... weird...

All the pods are running properly in k8s in Docker Desktop... so.. no errors...

It's simply not showing anything in BCN - SIMs...

**Comment by 3lcarry** [comment]
@CESARDELATORRE can you check the logs from the API pod? Can be related to the issue with CoreDNS?
If there is an error about login.microsoft.com unavailable try to change the DNS to 1.1.1.1 or 8.8.8.8

**Comment by 3lcarry** [comment]
I think it's related to the CoreDNS bug https://github.com/coredns/coredns/issues/5998, it's not happening always it's depends on the DNS server. 

As a workaround, instead of using the default system DNS, update to use the google or cloudfare DNS:

```
kubectl -n kube-system edit configmaps coredns -o yaml
```

Replace:
```
forward . /etc/resolv.conf {
    max_concurrent 1000
}
```
By:
```
forward . 1.1.1.1 {
    max_concurrent 1000
}
```
