### ISSUE TITLE
[P1] AMCREST Ethernet camera does NOT work on Control Plane cameras dashboard

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#133]
This is the AMCREST ethernet camera tested:

https://www.amazon.com/gp/product/B0BNM2SGPS/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/ca00532e-6cde-49c3-91f0-6c3b3f54597b)

This ethernet camera works from VLC Player in my LAN from my laptop:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/c9365889-548f-44b6-bf08-efcbc10ff081)

This is the RTSP string and how it was configured in the app:

rtsp://admin:Opensesame@172.30.1.155:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/bae01f11-0380-4bc1-b154-815cb20ed834)

In MEC-Accelerator app it works properly:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/8c77ec1b-d4da-4892-b959-9046acd6b396)

But it does NOT work in the control plane camera DASHBOARD:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/11e3b558-429f-495e-9200-3fed246a4200)

Related issues:

https://github.com/Azure/mec-app-solution-accelerator/issues/134

https://github.com/Azure/mec-app-solution-accelerator/issues/123

https://github.com/Azure/mec-app-solution-accelerator/issues/123

https://github.com/Azure/mec-app-solution-accelerator/issues/132

**Comment by 3lcarry** [comment]
This was related to a bug on the RTSP converter when camera id contains spaces. Its already fix.

**Comment by CESARDELATORRE** [comment]
Done
