### ISSUE TITLE
[P1] Add this OTHER Wi-Fi model camera to the system. (Amcrest 4MP ProHD Indoor WiFi/Ethernet) 

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#135]
Add this to MODEL and to automatically build the RTSP string:

Type: **Wi-Fi** AND **Ethernet**  (Add this cam to both, since it's Wi-Fi AND Ethernet)

Model:  **Amcrest 4MP ProHD Indoor WiFi/Ethernet**

Example RTSP:

`rtsp://MYUSER:MYPASSWORD@172.30.1.156:554/cam/realmonitor?channel=1&subtype=0`

This is the cam: :)

Amcrest 4MP ProHD Indoor WiFi, Security IP Camera with Pan/Tilt, Two-Way Audio, Night Vision, Remote Viewing, 4-Megapixel @30FPS, Wide 90° FOV, IP4M-1041W (White)

https://www.amazon.com/gp/product/B095XD17K5/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

<img width="400" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/b14dc9be-7360-4a66-ac0d-0f96d4571cbf">

**Comment by 3lcarry** [comment]
Model added to the list

**Comment by CESARDELATORRE** [comment]
Done
