### ISSUE TITLE
[P0] [BUG] Cameras Dashboard video shown is a loop of 5 secs video-clip instead of LIVE video

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#141]
Carlos, hay un BUG en el CAMERA DASHBOARD del control plane:
No se en que context, hay veces que la imagen de la camara se queda "En bucle" y repite todo el tiempo unos 5 segundos o asi en lugar de poner el video LIVE:
 
Pero luego creo una camara nueva y si lo saca LIVE, pero voy a otra pagina, vuelvo al camera dashboard y lo vuelvo a ver en bucle de pocos segundos... por que pasa eso?
 
Y yo creo que de hecho ese es el "refresh" raro que te comentaba que hacia la pagina, pero ahora he visto que hace eso cuando vuelve a recargar ese LOOP de unos 5 segundos. Lo he notado porque en video LIVE deberia cambiar cuando paso, etc. pero esta todo el tiempo "En bucle".
 
En cambio, si boro la camara, creo una nueva y voy al dashboard, la primera vez si que me muestra video LIVE.
Pero luego voy a otra pagina y vuelvo aqui, y entonces entra en el BUG (loop/clip de video de unos 5 segundos el mismo todo el rato) no se la razon...

**Comment by CESARDELATORRE** [comment]
@3lcarry Was this fixed already?

**Comment by 3lcarry** [comment]
@CESARDELATORRE yes, this was fix as part of this commit https://github.com/Azure/mec-app-solution-accelerator/commit/8e6b17dbaa79dc3f84ed78f2cfd6bdc154bbade0
