### ISSUE TITLE
[P0] Do not remove K8s Dashboard when un installing the app

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#148]
DO NOT do this or remove the dashboard neither in the Script:

    kubectl delete -f ./dashboard_auth/

It's better so have the dashboard installed to see how it was uninstalled, etc... or for other apps..

**Comment by virubiotor** [comment]
Fixed in ef2a4ed

**Comment by CESARDELATORRE** [comment]
Fixed, closing.
