### ISSUE TITLE
[P0] Error Permission related in docke compose up - PORT

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#149]
Error al usar docker compose up, relacionado con un puerto... pero parece algo de permisos, porque busco quien usa ese puerto y no lo tiene ningun process...
 
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:50064 -> 0.0.0.0:0: listen tcp 0.0.0.0:**50064**: bind: An attempt was made to access a socket **in a way forbidden by its access permissions.**
 
 
![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/209459cc-b64b-433f-befa-fc2cf6ba941f)

 
Ese es el puerto a usar por ALERTS-API:
 
  alerts-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Mqtt__ConnectionString=mosquitto
      - Mqtt__Port=1883
    ports:
      - "**50064**:80"
 
Pero como ves, mi maquina no esta usando ese puerto por ningun proceso mio...:
 
 
![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/6f89c345-f609-40c3-b579-c3021de58b4e)

 
Te ha pasado ese problema? Alguna idea?
[1:58 PM] Cesar De la Torre Llorente
De hecho si cambio el puerto al 50065, me da el mismo error. No parece un problema del PORT en concreto, mas algo de permissions?

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/b2c15807-9ade-4262-8c7c-dd5f42eea284)

**Comment by virubiotor** [comment]
There are certain ports that are taken by Hyper-V. I have changed the port used by docker-compose so that they are valid ones in dbd2041

**Comment by CESARDELATORRE** [comment]
Fixed, closing issue.
