### ISSUE TITLE
[P0] [BUG] Error in Solution when opening .sln in Visual Studio 2022

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#150]
Error in Solution when opening .sln in Visual Studio 2022

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/8538a47f-08a7-46d5-8714-0e67bdb0f901)

**Comment by virubiotor** [comment]
Fixed in 3105856

**Comment by CESARDELATORRE** [comment]
Fixed
