### ISSUE TITLE
[P0] BUG en Setup Script - "grep" in PowerShell ??

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#154]
grep doesn't work in Windows...

Please, test every update on all environments before pushing into GitHub...

ERROR:

grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/b182efe3-c9c1-48c5-885c-e94e222162fb)

.\deploy-accelerator.ps1 -kubernetesDistro k3s -mqttBroker mosquitto
Installing Mec-Accelerator with mosquitto MQTT broker
1. Installing Helm
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
3. Creating Mec-Accelerator namespace
namespace/mec-accelerator created
4. Installing Akri
"akri-helm-charts" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "akri-helm-charts" chart repository
...Successfully got an update from the "dapr" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
coalesce.go:289: warning: destination for akri.custom.configuration.discoveryDetails is a table. Ignoring non-table value ()
NAME: akri
LAST DEPLOYED: Fri May 10 14:50:50 2024
NAMESPACE: mec-accelerator
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the Akri Controller:
  kubectl get -o wide pods | grep controller
2. Get the Akri Agent(s):
  kubectl get -o wide pods | grep agent
3. Get the Akri Configuration(s):
  kubectl get -o wide akric
5. Deploying MQTT Broker
configmap/mqtt-config created
deployment.apps/mosquitto created
service/mosquitto created
6. Deploying Mec-Accelerator resources
namespace/mec-accelerator unchanged
configuration.dapr.io/dapr-config created
deployment.apps/alerts-api created
service/alerts-api created
service/alerts-ui created
deployment.apps/alerts-ui created
deployment.apps/files-management created
service/files-management created
deployment.apps/inference-model created
persistentvolumeclaim/minio-pvc created
deployment.apps/minio-deployment created
service/minio created
deployment.apps/mongodb-deployment created
service/mongodb created
deployment.apps/rulesengine created
service/rulesengine created
deployment.apps/zipkin created
service/zipkin created
persistentvolumeclaim/control-plane-mongodb-data created
deployment.apps/control-plane-mongodb-deployment created
service/control-plane-mongodb created
configmap/control-plane-api-config created
deployment.apps/control-plane-api-deployment created
service/control-plane-api-service created
deployment.apps/control-plane-ui-deployment created
service/control-plane-ui-service created
Warning: resource daemonsets/akri-camera-discovery-daemonset is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
daemonset.apps/akri-camera-discovery-daemonset configured
Warning: resource deployments/akri-controller-deployment is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.apps/akri-controller-deployment configured
Warning: resource configurations/akri-camera is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
configuration.akri.sh/akri-camera configured
Warning: resource serviceaccounts/akri-webhook-configuration is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
serviceaccount/akri-webhook-configuration configured
Warning: resource roles/akri-webhook-configuration is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
role.rbac.authorization.k8s.io/akri-webhook-configuration configured
Warning: resource rolebindings/akri-webhook-configuration is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
rolebinding.rbac.authorization.k8s.io/akri-webhook-configuration configured
Warning: resource deployments/akri-webhook-configuration is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.apps/akri-webhook-configuration configured
Warning: resource services/akri-webhook-configuration is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
service/akri-webhook-configuration configured
Warning: resource validatingwebhookconfigurations/akri-webhook-configuration is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
validatingwebhookconfiguration.admissionregistration.k8s.io/akri-webhook-configuration configured
serviceaccount/akri-webhook-configuration-patch created
clusterrole.rbac.authorization.k8s.io/akri-webhook-configuration-patch created
clusterrolebinding.rbac.authorization.k8s.io/akri-webhook-configuration-patch created
role.rbac.authorization.k8s.io/akri-webhook-configuration-patch created
rolebinding.rbac.authorization.k8s.io/akri-webhook-configuration-patch created
job.batch/akri-webhook-configuration-create created
job.batch/akri-webhook-configuration-patch created
deployment.apps/rtsp-converter-deployment created
service/rtsp-converter-service created
deployment.apps/rtsp-video-streamer created
service/rtsp-video-streamer created
secret/dapr-trust-bundle created
7. Deploying Kubernetes dashboards
namespace/kubernetes-dashboard created
serviceaccount/kubernetes-dashboard created
service/kubernetes-dashboard created
secret/kubernetes-dashboard-certs created
secret/kubernetes-dashboard-csrf created
secret/kubernetes-dashboard-key-holder created
configmap/kubernetes-dashboard-settings created
role.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
deployment.apps/kubernetes-dashboard created
service/dashboard-metrics-scraper created
deployment.apps/dashboard-metrics-scraper created
serviceaccount/admin-user created
clusterrolebinding.rbac.authorization.k8s.io/admin-user created
Kubernetes dashboards installed.
Please run 'kubectl proxy' to access the dashboard at http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
Generate a valid bearer token for the dashboard with 'kubectl -n kubernetes-dashboard create token admin-user --duration=48h --output yaml'
Successfully installed MEC-Accelerator!

Alerts-UI and Control-Plane-UI services deployed in:
grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Users\cesardl\GitHubRepos\mec-app-solution-accelerator-DEV-BRANCH-v1.9-NEW\deploy\k8s\deploy-accelerator.ps1:93 char:144
+ ... us.loadBalancer.ingress[*].ip,PORT:.spec.ports[*].port | grep -E 'ale ...
+                                                              ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by virubiotor** [comment]
Fixed in commit 9492d6f

**Comment by CESARDELATORRE** [comment]
Fixed, closing it.
