### ISSUE TITLE
[P0] Mobile Network Static IP pool is not 10.0.0.0/24 but 192.0.2.128/25

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#95]
Mobile Network Static IP pool is not 10.0.0.0/24 but 192.0.2.128/25

The query to REST APIs might be querying a wrong network?

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/7a5dd73d-25c4-4dd8-bf13-66bfc69e56f8)

You can see in AP5GC in Azure portal that in our particular packet core the IP rage is:

`192.0.2.128/25`

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/826c5f9f-dd1d-4528-8814-8875b84f705b)

**Comment by 3lcarry** [comment]
@CESARDELATORRE I've pushed new images fixing this issue. The functionality was only implemented on the ui and the ip was mock data.

**Comment by CESARDELATORRE** [comment]
This is implemented and works for me. Great! :) 

Closing it!
